#!/bin/bash

dir="$(dirname "$0")"

MLTOOLS="$dir/data/machinelearning.list"

# Install preferred machine learning tools
function machinelearning {
	if (eval `resize` && whiptail \
		--title "Machine Learning" \
		--yesno "Install ML tools?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext) then
		show_info 'Installing...'
		show_warning 'Requires root privileges'
    # Update pip
    pip3.6 install --upgrade pip
		# For loop for installing
		for PACKAGE in $(cat $MLTOOLS)
		do
			# Check if package is installed
			PKGCHECK=$(pip3.6 list --format=legacy | grep "$PACKAGE")
			if [ "" == "$PKGCHECK" ]; then
				show_info "pip package '$PACKAGE' is not installed. Installing..."
				# Install package
				pip3.6 install --user $PACKAGE
				show_success 'Done.'
			else
				show_success "Package '$PACKAGE' is installed."
			fi
		done
		show_success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of ML tools complete." 8 78
		main
	else
		main
	fi
}
