#!/bin/bash

dir="$(dirname "$0")"

DRIVERS="$dir/data/nvidia.list"

# Install preferred development applications using the list of packages 'data/development.list'
function nvidia {
	if (eval `resize` && whiptail \
		--title "NVIDIA Drivers" \
		--yesno "Drivers to install: \n\n$(cat $DEVTOOLS) \n\nProceed with installation?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext) then
		show_info 'Installing...'
		show_warning 'Requires root privileges'
		# For loop for installing
		for PACKAGE in $(cat $DRIVERS)
		do
			# Check if package is installed
			PKGCHECK=$(dnf list installed | grep "$PACKAGE")
			if [ "" == "$PKGCHECK" ]; then
				show_info "Package '$PACKAGE' is not installed. Installing..."
				# Install package
				sudo dnf install -y $PACKAGE
				show_success 'Done.'
			else
				show_success "Package '$PACKAGE' is installed."
			fi
		done
		# Wayland Support
		dnf copr enable mati865/mutter-eglstream
		dnf --disablerepo="*" --enablerepo="mati865-mutter-eglstream" reinstall mutter
		# // Wayland Support
		show_success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of NVIDIA drivers complete." 8 78
		main
	else
		main
	fi
}

